"use client";

import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogDescription,
} from "@/components/ui/dialog";
import { Sparkles } from "lucide-react";
import { ScrollArea } from "./ui/scroll-area";

interface SummaryDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  summary: string;
}

export function SummaryDialog({ open, onOpenChange, summary }: SummaryDialogProps) {
  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2 font-headline">
            <Sparkles className="h-5 w-5 text-primary" />
            AI Generated Summary
          </DialogTitle>
          <DialogDescription>
            Here's a quick summary of your note, generated by AI.
          </DialogDescription>
        </DialogHeader>
        <ScrollArea className="max-h-80 rounded-md border p-4">
            <p className="text-sm leading-relaxed">{summary}</p>
        </ScrollArea>
      </DialogContent>
    </Dialog>
  );
}
